version: '3.8'  

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "4173:4173"
 
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - frontend